services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\SubColumnsBootstrapBundle\:
    resource: '../src/{Asset,DataContainer,EventListener,Migration}/*'
    public: true
