services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $projectDir: '%kernel.project_dir%'

  HeimrichHannot\SubColumnsBootstrapBundle\:
    resource: '../src/{Asset,Controller,DataContainer,EventListener,FormField,Migration}/*'
    public: true
